//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int ID { get; set; }
        public string SupplierName { get; set; }
        public int TaxNumber { get; set; }
        public string TaxUnit { get; set; }
        public string Address { get; set; }
        public System.DateTime AddedDate { get; set; }
    }
}
